# Generated by Django 4.0.2 on 2023-05-03 09:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='compiler.directory')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='compiler.directory')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200, null=True)),
                ('description', models.CharField(default=None, max_length=200, null=True)),
                ('date_created', models.DateTimeField(default=datetime.date.today)),
                ('begin', models.IntegerField(default=None, null=True)),
                ('end', models.IntegerField(default=None, null=True)),
                ('type', models.CharField(max_length=200)),
                ('status', models.CharField(default=None, max_length=200, null=True)),
                ('text', models.CharField(max_length=2000)),
                ('file', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='compiler.file')),
            ],
        ),
    ]
