# Generated by Django 4.0.2 on 2023-05-03 00:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='compiler.directory')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200, null=True)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='compiler.directory')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200, null=True)),
                ('description', models.CharField(default=None, max_length=200, null=True)),
                ('date_created', models.DateTimeField(default=datetime.date.today)),
                ('begin', models.IntegerField(default=None, null=True)),
                ('end', models.IntegerField(default=None, null=True)),
                ('type', models.CharField(max_length=200)),
                ('status', models.CharField(default=None, max_length=200, null=True)),
                ('text', models.CharField(max_length=2000)),
                ('file', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='compiler.file')),
            ],
        ),
        migrations.DeleteModel(
            name='Element',
        ),
    ]
