# Generated by Django 4.0.2 on 2023-05-03 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0003_directory_accessibility_directory_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='accessibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='file',
            name='date_created',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='last_accessibility_change',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='last_content_change',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
