# Generated by Django 4.0.2 on 2023-05-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0005_alter_file_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='status_data',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='begin',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='section',
            name='end',
            field=models.IntegerField(default=None),
        ),
    ]
