# Generated by Django 4.0.2 on 2023-05-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0006_section_status_data_alter_section_begin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directory',
            old_name='accessibility',
            new_name='access',
        ),
        migrations.RenameField(
            model_name='directory',
            old_name='last_accessibility_change',
            new_name='last_access_change',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='accessibility',
            new_name='access',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='last_accessibility_change',
            new_name='last_access_change',
        ),
    ]
