# Generated by Django 4.0.2 on 2023-05-09 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0008_alter_directory_date_created_alter_file_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='section',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
