# Generated by Django 4.0.2 on 2023-05-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0009_alter_directory_date_created_alter_file_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
